name: Deploy React App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set working directory
        run: echo "PROJECT_DIR=chotacopnew" >> $GITHUB_ENV  # Use your actual project directory name

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: npm install

      - name: Build the React app
        working-directory: ${{ env.PROJECT_DIR }}
        run: npm run build

      - name: List contents of dist folder
        run: ls -R dist  # This helps to debug the contents of the dist folder

      - name: Copy build folder to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/**/*"  # Updated to use 'dist' folder recursively
          target: "/var/www/yi.crivo.in"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo systemctl reload nginx

